# Generated by Django 4.2.2 on 2023-07-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy_app', '0004_remove_meetup_end_time_meetup_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
